<?php include 'views/layouts/header.php'; ?>
<?php
$rows = $rows ?? []; $stats = $stats ?? []; $filters = $filters ?? [];
$tipos = ['antena' => ['Antena','fa-satellite-dish','primary'], 'modem' => ['Módem','fa-ethernet','success'], 'switch' => ['Switch','fa-network-wired','warning'], 'access_point' => ['Access Point','fa-tower-broadcast','purple'], 'router' => ['Router','fa-wifi','info'], 'otro' => ['Otro','fa-microchip','secondary']];
$estados = ['operativo' => ['Operativo','success'], 'en_mantenimiento' => ['En mantenimiento','warning'], 'necesita_revision' => ['Necesita revisión','primary'], 'fuera_de_servicio' => ['Fuera de servicio','danger'], 'dañado' => ['Dañado','danger']];
$porCliente = [];
foreach ($rows as $row) { $porCliente[(int)$row['cliente_id']][] = $row; }
function repFecha($value, $withTime = false) { $ts = $value ? strtotime($value) : false; return $ts ? date($withTime ? 'd/m/Y H:i' : 'd/m/Y', $ts) : '—'; }
function repEquipoNombre($row) { $name = trim(($row['marca'] ?? '') . ' ' . ($row['modelo'] ?? '')); return $name ?: 'Equipo #' . (int)$row['id']; }
?>
<style>
.equipos-report-header{margin:1.25rem 0}.report-hero-icon{width:48px;height:48px;border-radius:15px;display:grid;place-items:center;color:#fff;background:linear-gradient(135deg,#2563eb,#0ea5e9);box-shadow:0 12px 24px rgba(37,99,235,.24)}
.kpi-card{border:1px solid rgba(15,23,42,.06);border-radius:16px;transition:transform .2s,box-shadow .2s}.kpi-card:hover{transform:translateY(-2px);box-shadow:0 12px 26px rgba(15,23,42,.09)}.kpi-label{font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;font-weight:800;color:#64748b}.kpi-value{font-weight:800;font-size:1.5rem;color:#0f172a}
.client-accordion{border:1px solid rgba(15,23,42,.08);border-radius:16px;overflow:hidden;box-shadow:0 3px 12px rgba(15,23,42,.04)}.client-accordion+.client-accordion{margin-top:1rem}.client-toggle{width:100%;border:0;background:#fff;text-align:left;padding:1.1rem 1.25rem}.client-toggle:hover{background:#f8fafc}.client-toggle:not(.collapsed){background:#f8fbff;box-shadow:none}.client-toggle:focus{box-shadow:inset 0 0 0 2px rgba(37,99,235,.25)}.client-toggle::after{margin-left:1rem}.client-avatar{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;background:#dbeafe;color:#1d4ed8;font-weight:800}.client-name{font-size:1rem;font-weight:800;color:#0f172a}.client-summary{font-size:.79rem;color:#64748b}.type-badge{font-size:.72rem;font-weight:700;padding:.35rem .55rem;border-radius:999px}.type-primary{background:#dbeafe;color:#1d4ed8}.type-success{background:#dcfce7;color:#15803d}.type-warning{background:#fef3c7;color:#a16207}.type-purple{background:#f3e8ff;color:#7e22ce}.type-info{background:#cffafe;color:#0e7490}.type-secondary{background:#e2e8f0;color:#475569}.estado-badge{font-size:.72rem;border-radius:999px;padding:.35rem .55rem}.client-table{font-size:.86rem}.client-table thead th{font-size:.67rem;text-transform:uppercase;letter-spacing:.07em;color:#64748b;background:#f8fafc;white-space:nowrap}.client-table td{vertical-align:middle}.client-table tbody tr{cursor:pointer;transition:background .16s}.client-table tbody tr:hover{background:#eff6ff}.equipment-icon{width:30px;height:30px;border-radius:9px;display:inline-grid;place-items:center}.wifi-on{color:#16a34a}.wifi-off{color:#94a3b8}.filter-card{border:1px solid rgba(15,23,42,.07);border-radius:16px}.table-responsive{max-height:480px}.accordion-body{background:#fff}@media print{.sidebar,.app-topbar,.report-actions,.filter-card{display:none!important}main{width:100%!important;max-width:100%!important}.collapse{display:block!important}}
</style>

<div class="equipos-report-header d-flex flex-wrap align-items-center justify-content-between gap-3">
 <div class="d-flex align-items-center gap-3"><div class="report-hero-icon"><i class="fas fa-router"></i></div><div><h1 class="h3 mb-1 fw-bold">Equipos instalados</h1><p class="text-muted mb-0">Inventario organizado por cliente e instalación.</p></div></div>
 <div class="report-actions d-flex gap-2"><a href="<?php echo url('reportes'); ?>" class="btn btn-outline-secondary"><i class="fas fa-arrow-left me-1"></i>Volver</a><button class="btn btn-outline-secondary" onclick="window.print()"><i class="fas fa-print me-1"></i>Imprimir</button></div>
</div>

<div class="row g-3 mb-3">
<?php foreach ([['Clientes',$stats['clientes'] ?? 0,'fa-users','primary'],['Equipos',$stats['total'] ?? 0,'fa-cubes','info'],['Antenas',$stats['antenas'] ?? 0,'fa-satellite-dish','primary'],['Módems',$stats['modems'] ?? 0,'fa-ethernet','success'],['Switches',$stats['switches'] ?? 0,'fa-network-wired','warning'],['Access Points',$stats['access_points'] ?? 0,'fa-tower-broadcast','purple'],['Operativos',$stats['operativos'] ?? 0,'fa-circle-check','success'],['Mantenimiento',$stats['mantenimiento'] ?? 0,'fa-screwdriver-wrench','warning'],['Fuera de servicio',$stats['fuera_servicio'] ?? 0,'fa-circle-xmark','danger']] as $kpi): ?>
 <div class="col-6 col-md-4 col-xl"><div class="card kpi-card h-100"><div class="card-body p-3"><div class="d-flex justify-content-between align-items-start"><div><div class="kpi-label"><?php echo $kpi[0]; ?></div><div class="kpi-value mt-1"><?php echo (int)$kpi[1]; ?></div></div><i class="fas <?php echo $kpi[2]; ?> text-<?php echo $kpi[3] === 'purple' ? 'primary' : $kpi[3]; ?>"></i></div></div></div></div>
<?php endforeach; ?>
</div>

<div class="card filter-card mb-3"><div class="card-body"><form method="GET" action="<?php echo url('reportes/equipos-instalados'); ?>"><div class="row g-2 align-items-end">
 <div class="col-md-4 col-lg-3"><label class="form-label small">Buscar cliente</label><input class="form-control" name="cliente" value="<?php echo htmlspecialchars($filters['cliente'] ?? ''); ?>" placeholder="Nombre o teléfono"></div>
 <div class="col-md-4 col-lg-2"><label class="form-label small">MAC</label><input class="form-control" name="mac_address" value="<?php echo htmlspecialchars($filters['mac_address'] ?? ''); ?>" placeholder="AA:BB:CC"></div>
 <div class="col-md-4 col-lg-2"><label class="form-label small">IP</label><input class="form-control" name="direccion_ip" value="<?php echo htmlspecialchars($filters['direccion_ip'] ?? ''); ?>" placeholder="192.168..."></div>
 <div class="col-md-4 col-lg-2"><label class="form-label small">N.º de serie</label><input class="form-control" name="numero_serie" value="<?php echo htmlspecialchars($filters['numero_serie'] ?? ''); ?>"></div>
 <div class="col-md-4 col-lg-2"><label class="form-label small">Tipo</label><select class="form-select" name="tipo_equipo"><option value="">Todos</option><?php foreach($tipos as $key=>$tipo): ?><option value="<?php echo $key; ?>" <?php echo ($filters['tipo_equipo'] ?? '') === $key ? 'selected' : ''; ?>><?php echo $tipo[0]; ?></option><?php endforeach; ?></select></div>
 <div class="col-md-4 col-lg-2"><label class="form-label small">Estado técnico</label><select class="form-select" name="estado_tecnico"><option value="">Todos</option><?php foreach($estados as $key=>$estado): ?><option value="<?php echo $key; ?>" <?php echo ($filters['estado_tecnico'] ?? '') === $key ? 'selected' : ''; ?>><?php echo $estado[0]; ?></option><?php endforeach; ?></select></div>
 <div class="col-md-4 col-lg-2"><label class="form-label small">Acceso módem</label><select class="form-select" name="estado_acceso"><option value="">Todos</option><option value="activo" <?php echo ($filters['estado_acceso'] ?? '') === 'activo' ? 'selected' : ''; ?>>WiFi encendido</option><option value="inactivo" <?php echo ($filters['estado_acceso'] ?? '') === 'inactivo' ? 'selected' : ''; ?>>WiFi apagado</option></select></div>
 <div class="col-md-4 col-lg-2"><label class="form-label small">Instalado desde</label><input type="date" class="form-control" name="fecha_desde" value="<?php echo htmlspecialchars($filters['fecha_desde'] ?? ''); ?>"></div>
 <div class="col-md-4 col-lg-2"><label class="form-label small">Hasta</label><input type="date" class="form-control" name="fecha_hasta" value="<?php echo htmlspecialchars($filters['fecha_hasta'] ?? ''); ?>"></div>
 <div class="col-md-4 col-lg-2 d-flex gap-2"><button class="btn btn-primary flex-grow-1"><i class="fas fa-filter me-1"></i>Filtrar</button><a class="btn btn-outline-secondary" href="<?php echo url('reportes/equipos-instalados'); ?>" title="Restablecer"><i class="fas fa-rotate"></i></a></div>
</div></form></div></div>

<div class="d-flex align-items-center justify-content-between mb-2"><div><h2 class="h5 mb-0 fw-bold">Clientes con equipos</h2><span class="small text-muted"><?php echo count($porCliente); ?> clientes · <?php echo count($rows); ?> equipos encontrados</span></div></div>
<div class="accordion" id="clientesEquiposAccordion">
<?php foreach ($porCliente as $clienteId => $equipos): $primero=$equipos[0]; $counts=['operativo'=>0,'en_mantenimiento'=>0,'fuera_de_servicio'=>0]; $tiposCliente=[]; foreach($equipos as $item){$estado=$item['estado_tecnico']??''; if(isset($counts[$estado]))$counts[$estado]++; $tiposCliente[$item['tipo_equipo']??'otro']=true;} ?>
 <div class="client-accordion"><h2 class="accordion-header" id="clienteHeading<?php echo $clienteId; ?>"><button class="client-toggle accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#cliente<?php echo $clienteId; ?>" aria-expanded="false" aria-controls="cliente<?php echo $clienteId; ?>"><span class="client-avatar me-3"><?php echo htmlspecialchars(strtoupper(substr($primero['cliente_nombre'] ?? 'C',0,1))); ?></span><span class="flex-grow-1"><span class="client-name d-block"><?php echo htmlspecialchars($primero['cliente_nombre'] ?? 'Cliente'); ?></span><span class="client-summary"><?php echo count($equipos); ?> equipos · <?php echo $counts['operativo']; ?> operativos · <?php echo $counts['en_mantenimiento']; ?> en mantenimiento · <?php echo $counts['fuera_de_servicio']; ?> fuera de servicio</span></span><span class="d-none d-md-flex gap-1 flex-wrap me-2"><?php foreach(array_keys($tiposCliente) as $tipoKey): $tipo=$tipos[$tipoKey]??$tipos['otro']; ?><span class="type-badge type-<?php echo $tipo[2]; ?>"><i class="fas <?php echo $tipo[1]; ?> me-1"></i><?php echo $tipo[0]; ?></span><?php endforeach; ?></span></button></h2>
 <div id="cliente<?php echo $clienteId; ?>" class="accordion-collapse collapse" aria-labelledby="clienteHeading<?php echo $clienteId; ?>" data-bs-parent="#clientesEquiposAccordion"><div class="accordion-body p-0"><div class="table-responsive"><table class="table client-table mb-0"><thead><tr><th class="ps-3">Tipo / equipo</th><th>Marca / modelo</th><th>Serie</th><th>MAC / IP</th><th>Instalación</th><th>Estado técnico</th><th>Acceso</th><th>Actualizado</th><th class="text-end pe-3">Acciones</th></tr></thead><tbody>
 <?php foreach($equipos as $equipo): $tipoKey=$equipo['tipo_equipo']??'otro'; $tipo=$tipos[$tipoKey]??$tipos['otro']; $estado=$estados[$equipo['estado_tecnico']??'']??['Sin estado','secondary']; ?>
 <tr data-href="<?php echo url('equipos/' . (int)$equipo['id']); ?>" tabindex="0" role="link" aria-label="Ver <?php echo htmlspecialchars(repEquipoNombre($equipo)); ?>"><td class="ps-3"><span class="equipment-icon type-<?php echo $tipo[2]; ?> me-2"><i class="fas <?php echo $tipo[1]; ?>"></i></span><span class="fw-semibold"><?php echo $tipo[0]; ?></span><div class="small text-muted ms-5"><?php echo htmlspecialchars(repEquipoNombre($equipo)); ?></div></td><td><?php echo htmlspecialchars($equipo['marca'] ?: '—'); ?><div class="small text-muted"><?php echo htmlspecialchars($equipo['modelo'] ?: ''); ?></div></td><td><code><?php echo htmlspecialchars($equipo['numero_serie'] ?: '—'); ?></code></td><td><div><?php echo htmlspecialchars($equipo['mac_address'] ?: '—'); ?></div><div class="small text-muted"><?php echo htmlspecialchars($equipo['direccion_ip'] ?: ''); ?></div></td><td><?php echo repFecha($equipo['fecha_instalacion']); ?></td><td><span class="badge bg-<?php echo $estado[1]; ?> estado-badge"><?php echo $estado[0]; ?></span></td><td><?php if($tipoKey==='modem'): ?><span title="<?php echo !empty($equipo['acceso_habilitado'])?'WiFi encendido':'WiFi apagado'; ?>"><i class="fas fa-wifi <?php echo !empty($equipo['acceso_habilitado'])?'wifi-on':'wifi-off'; ?> me-1"></i><?php echo !empty($equipo['acceso_habilitado'])?'Activo':'Apagado'; ?></span><?php else: ?>—<?php endif; ?></td><td><?php echo repFecha($equipo['updated_at'],true); ?></td><td class="text-end pe-3"><a class="btn btn-sm btn-outline-primary row-action" href="<?php echo url('equipos/' . (int)$equipo['id']); ?>" title="Ver detalle"><i class="fas fa-arrow-up-right-from-square"></i></a></td></tr>
 <?php endforeach; ?></tbody></table></div></div></div></div>
<?php endforeach; ?>
</div>
<?php if (empty($porCliente)): ?><div class="card border-0 shadow-sm"><div class="card-body py-5 text-center"><i class="fas fa-inbox fa-2x text-muted mb-3"></i><h3 class="h6">No hay equipos para mostrar</h3><p class="text-muted small mb-0">Ajusta los filtros o registra un equipo nuevo.</p></div></div><?php endif; ?>
<script>document.querySelectorAll('tr[data-href]').forEach(function(row){var detailUrl=row.dataset.href;var actions=row.querySelector('td:last-child');if(actions){actions.innerHTML='<div class="btn-group btn-group-sm row-action"><a class="btn btn-outline-primary" href="'+detailUrl+'" title="Ver detalle"><i class="fas fa-eye"></i></a><a class="btn btn-outline-warning" href="'+detailUrl+'/edit" title="Editar equipo"><i class="fas fa-pen"></i></a><form method="post" action="'+detailUrl+'/delete" onsubmit="return confirm(\'¿Eliminar este equipo y sus visitas técnicas? Esta acción no se puede deshacer.\');"><button type="submit" class="btn btn-outline-danger" title="Eliminar equipo"><i class="fas fa-trash"></i></button></form></div>';}row.addEventListener('click',function(e){if(!e.target.closest('a,button,input,select,label,form'))window.location=detailUrl;});row.addEventListener('keydown',function(e){if(e.key==='Enter')window.location=detailUrl;});});</script>
<?php include 'views/layouts/footer.php'; ?>
