<?php include 'views/layouts/header.php';
$rows = $rows ?? []; $filters = $filters ?? []; $kpis = $kpis ?? [];
$query = http_build_query(array_filter($filters));
?>
<style>
.payment-report-logo { width: 130px; height: 72px; object-fit: contain; background:#050505; border-radius:.5rem; }
@media print { .sidebar,.app-topbar,.no-print,.btn,form { display:none!important; } main { width:100%!important; padding:0!important; } .card { box-shadow:none!important; } }
</style>
<div class="d-flex justify-content-between align-items-center flex-wrap gap-3 pt-3 pb-3">
  <div class="d-flex align-items-center gap-3"><img class="payment-report-logo" src="<?php echo url('public/sky-network-logo.png'); ?>" alt="Sky Network"><div><h1 class="h3 mb-1">Reporte de Pagos y Corte de Caja</h1><p class="text-muted mb-0">Ingresos, cobranzas, vencimientos y detalle por cliente.</p></div></div>
  <div class="no-print d-flex gap-2"><a class="btn btn-outline-success" href="<?php echo url('reportes/pagos/excel') . ($query ? '?' . $query : ''); ?>"><i class="fas fa-file-excel me-1"></i>Excel</a><button class="btn btn-danger" onclick="window.print()"><i class="fas fa-file-pdf me-1"></i>Guardar PDF</button></div>
</div>
<form class="card card-body mb-3 no-print" method="get">
 <div class="row g-2"><div class="col-md-3"><label class="form-label">Desde</label><input class="form-control" type="date" name="fecha_desde" value="<?php echo htmlspecialchars($filters['fecha_desde'] ?? ''); ?>"></div><div class="col-md-3"><label class="form-label">Hasta</label><input class="form-control" type="date" name="fecha_hasta" value="<?php echo htmlspecialchars($filters['fecha_hasta'] ?? ''); ?>"></div><div class="col-md-2"><label class="form-label">Estado</label><select name="estado" class="form-select"><option value="">Todos</option><?php foreach(['pagado'=>'Pagado','pendiente'=>'Pendiente','vencido'=>'Vencido'] as $v=>$l): ?><option value="<?php echo $v; ?>" <?php echo ($filters['estado']??'')===$v?'selected':''; ?>><?php echo $l; ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Método</label><input class="form-control" name="metodo" value="<?php echo htmlspecialchars($filters['metodo'] ?? ''); ?>" placeholder="Efectivo, tarjeta..."></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Aplicar filtros</button></div></div>
</form>
<div class="row g-3 mb-3"><div class="col-md-3"><div class="card card-body"><small class="text-muted">Ingresos del mes</small><strong class="fs-4">$<?php echo number_format((float)($kpis['ingresos_mes']??0),2); ?></strong></div></div><div class="col-md-3"><div class="card card-body"><small class="text-muted">Pagados este mes</small><strong class="fs-4"><?php echo (int)($kpis['pagos_realizados_mes']??0); ?></strong></div></div><div class="col-md-3"><div class="card card-body"><small class="text-muted">Pendientes</small><strong class="fs-4 text-warning"><?php echo (int)($kpis['pagos_pendientes']??0); ?></strong></div></div><div class="col-md-3"><div class="card card-body"><small class="text-muted">Clientes vencidos</small><strong class="fs-4 text-danger"><?php echo (int)($kpis['clientes_vencidos']??0); ?></strong></div></div></div>
<div class="card"><div class="card-header d-flex justify-content-between"><strong>Detalle de pagos</strong><small class="text-muted"><?php echo count($rows); ?> registros</small></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Cliente</th><th>Factura</th><th>Pago</th><th>Vence</th><th>Estado</th><th>Método</th><th>Meses</th><th class="text-end">Monto</th></tr></thead><tbody><?php if (!$rows): ?><tr><td colspan="8" class="text-center text-muted py-4">No hay pagos registrados para los filtros seleccionados.</td></tr><?php endif; ?><?php foreach($rows as $row): ?><tr><td><?php echo htmlspecialchars($row['cliente_nombre']); ?></td><td><?php echo htmlspecialchars($row['numero_factura']); ?></td><td><?php echo $row['fecha_pago'] ? date('d/m/Y',strtotime($row['fecha_pago'])) : '-'; ?></td><td><?php echo $row['fecha_vencimiento'] ? date('d/m/Y',strtotime($row['fecha_vencimiento'])) : '-'; ?></td><td><span class="badge bg-<?php echo $row['estado']==='pagado'?'success':($row['estado']==='vencido'?'danger':'warning'); ?>"><?php echo ucfirst($row['estado']); ?></span></td><td><?php echo htmlspecialchars($row['metodo_pago']); ?></td><td><?php echo (int)$row['meses_pagados_cliente']; ?></td><td class="text-end">$<?php echo number_format((float)$row['monto'],2); ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php include 'views/layouts/footer.php'; ?>
